In [51]:
import numpy as np

def matricedecompo(v,k):
    n = len(v)
    M = np.zeros((n,n))
    for i in range(n//2**k):
        M[i][2*i] = 1/2
        M[i][2*i+1] = 1/2
    j=0
    for i in range(n//2**k,n//k):
        M[i][2*j] = -1/2
        M[i][2*j+1] = 1/2
        j+=1
    if k>1:
        for i in range(n//k,n):
            M[i][i]=1
    return M

# exemple
v = [7,1,6,6]
M = matricedecompo(v,1)

x = np.zeros((4,4))
(l,c)=x.shape

for i in range(l):
    for j in range(c):
        x[i][j] = i+j*j
print(x)

[[ 0.  1.  4.  9.]
 [ 1.  2.  5. 10.]
 [ 2.  3.  6. 11.]
 [ 3.  4.  7. 12.]]


In [52]:
for i in range(l):
    print(np.dot(M,x[i:i+1][0]))
    
print("\n",M)

[0.5 6.5 0.5 2.5]
[1.5 7.5 0.5 2.5]
[2.5 8.5 0.5 2.5]
[3.5 9.5 0.5 2.5]

 [[ 0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5]
 [-0.5  0.5  0.   0. ]
 [ 0.   0.  -0.5  0.5]]


In [53]:
for i in range(c):
    print(np.dot(M,x[0:c][i]))
    
print("\n",M)

[0.5 6.5 0.5 2.5]
[1.5 7.5 0.5 2.5]
[2.5 8.5 0.5 2.5]
[3.5 9.5 0.5 2.5]

 [[ 0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5]
 [-0.5  0.5  0.   0. ]
 [ 0.   0.  -0.5  0.5]]


In [69]:
print(np.dot(I,x[0:c,3]))

x[0:c,3]

[ 9. 10. 11. 12.]


array([ 9., 10., 11., 12.])

In [71]:
I=np.identity(l)

for i in range(l):
    print(np.dot(I,x[i:i+1][0]))
    
for i in range(c):
    print(np.dot(I,x[0:c,i]))
   

[0. 1. 4. 9.]
[ 1.  2.  5. 10.]
[ 2.  3.  6. 11.]
[ 3.  4.  7. 12.]
[0. 1. 2. 3.]
[1. 2. 3. 4.]
[4. 5. 6. 7.]
[ 9. 10. 11. 12.]


In [80]:
import copy

y = copy.deepcopy(x)
y[0][0] = 1000
y[0:6//2]

array([[1000.,    1.,    4.,    9.],
       [   1.,    2.,    5.,   10.],
       [   2.,    3.,    6.,   11.]])

In [98]:
x = np.zeros((512,512))
(l,c)=x.shape
print(len(x))
for i in range(l):
    for j in range(c):
        x[i][j] = 1

for i in range(3):
    x=x[0:l//2**i,0:l//2**i]
    print(len(x),len(x[0]),"\n")

512
512 512 

256 256 

128 128 



In [99]:
512/4

128.0